USE weGotData;
INSERT INTO restaurants (name, place_id, rating) VALUES ("Clift San Francisco", "ChIJFUBxSY6AhYARwOaLV7TsLjw", 4.1);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Hotel Fusion", "ChIJ0SMraI-AhYAREeJAvm2_yGM", 3.6);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Cornell Hotel De France", "ChIJs6F3JYyAhYARDiVdBrmivCs", 4.2);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Fairmont San Francisco", "ChIJN2S4EI2AhYAR9J4Qeh1U8Aw", 4.5);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Le Méridien San Francisco", "ChIJcWfgM2CAhYARD19rCAPLhVU", 4.3);
INSERT INTO restaurants (name, place_id, rating) VALUES ("La Mar Cebicheria Peruana", "ChIJURDKN2eAhYARN0AMzUEaiKo", 4.4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Comstock Saloon", "ChIJ18LA7PSAhYARZCNy_dme7v8", 4.5);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Credo", "ChIJIbtvA4qAhYARdnwerOi-f4I", 4.1);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Local Kitchen & Wine Merchant", "ChIJzWMEoXuAhYARnGNx8NeVTpY", 4.1);
INSERT INTO restaurants (name, place_id, rating) VALUES ("54 Mint SF", "ChIJP5PrLYSAhYARBcWhJXs55P4", 4.2);
INSERT INTO restaurants (name, place_id, rating) VALUES ("The Grove - Yerba Buena", "ChIJiZyN7IeAhYARnCn-G6GH73Q", 4.3);
INSERT INTO restaurants (name, place_id, rating) VALUES ("The Stinking Rose", "ChIJW52Si_OAhYAR-jAC1-iQh_c", 3.9);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Benu", "ChIJSToWqn2AhYAR1CuH2iGMvuo", 4.6);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Boulevard Restaurant", "ChIJF-zbSmSAhYARvOafjdCRszQ", 4.4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Lers Ros", "ChIJZduCKJGAhYARueNvSMvqsUI", 4.3);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Park Tavern", "ChIJNRipBPGAhYAR1qLFGG_Tby4", 4.4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Westfield San Francisco Centre", "ChIJ6zMe3oWAhYARaZ33Z1BAMRo", 4.3);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Rogue Ales Public House", "ChIJK6Yru_GAhYARLzuWvZIgCc4", 4.2);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Southern Pacific Brewing", "ChIJn5G9Fzp-j4ARRs66QTw4XAY", 4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Perbacco", "ChIJNy8VmmGAhYARQF84_9twEc4", 4.3);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Daily Grill", "ChIJl7zcHY-AhYAR4rDx9C6-N4s", 4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Taverna Aventine", "ChIJk2EFyIqAhYARXlKs2zO34Fg", 4.2);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Tacolicious", "ChIJaQ1QHj1-j4ARGwFcVV3HM9A", 4.3);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Cafe Asia", "ChIJkQQVTZqAhYARYZQeCiUWMPE", 3.4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("The Creamery", "ChIJ8YUefdZ_j4ART8gb7SJeblY", 4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Mission Bowling Club", "ChIJ10DmyyR-j4ARBZDBrVVevpo", 4.4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Jardinière", "ChIJKxsc-5iAhYARt0aq9Skp6t8", 4.2);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Jones", "ChIJPR_P35GAhYAR6wRwwtF7pnE", 4.1);
INSERT INTO restaurants (name, place_id, rating) VALUES ("One Market Restaurant", "ChIJDVK5qGaAhYAR_goq49KaaEc", 4.1);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Focaccia Market Bakery", "ChIJkztvQGGAhYARS9PBosvWB5o", 3.8);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Extreme Pizza", "ChIJj2vPJNuAhYARSgmTp9KnaxQ", 3.7);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Sens", "ChIJBVDZR2GAhYARCy82N8HgD5I", 4.2);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Zuni Café", "ChIJO7u9q5-AhYARiSSXyWv9eJ8", 4.1);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Coqueta", "ChIJA8_SN2eAhYARCIvEx44Zvfw", 4.3);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Kokkari Estiatorio", "ChIJTel9dGCAhYARQGwrTfGZ07M", 4.6);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Ruth's Chris Steak House", "ChIJyQ2vy-qAhYARnNuxU_WWsKk", 4.3);
INSERT INTO restaurants (name, place_id, rating) VALUES ("farmerbrown", "ChIJv-klmoWAhYAReflECbnTyRE", 4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("The Slanted Door", "ChIJWTGPjmaAhYARnYsfhjHT8JM", 4.2);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Cafe Bistro", "ChIJ6zMe3oWAhYARCjdEkUhwnm8", 4.4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Marlowe", "ChIJK08gKtR_j4ARKyo5suJ6o2I", 4.3);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Jasper's Corner Tap and Kitchen", "ChIJsYeEyY-AhYARFukSYv7t_3Q", 3.7);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Farallon", "ChIJJ0yB8o6AhYAR0HIFmCURzGc", 4.3);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Wayfare Tavern", "ChIJE5T3YoqAhYARtxUohSbFVDc", 4.4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Fog City", "ChIJYSMTLPaAhYARFZCDlJ6yMr0", 3.8);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Nopa", "ChIJ_dQjyK-AhYARBc9DFlxcclg", 4.5);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Franciscan Crab Restaurant", "ChIJERGFHOOAhYARFYtaHpvXbyc", 4.1);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Ramen Underground", "ChIJyyQu04uAhYARXVI2yERHvEk", 4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("The Cavalier", "ChIJUUjhfoaAhYARRuSNp1R18vs", 4.2);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Hog Island Oyster Co.", "ChIJWTGPjmaAhYARgXpiJ-aACYM", 4.5);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Hakkasan", "ChIJZR1IXIiAhYARVdRHncWNWRY", 4.4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Waterbar", "ChIJgXkuGnCAhYARbVYisXVfO68", 4.4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("The Boardroom", "ChIJCxXWkPGAhYARXwt61gGhLl8", 4.5);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Brenda's French Soul Food", "ChIJZ9s5SJeAhYARIX3Fxl6oj6c", 4.5);
INSERT INTO restaurants (name, place_id, rating) VALUES ("ThirstyBear Brewing Company", "ChIJ39DPC32AhYARAoTh-QZjrN8", 3.7);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Rich Table", "ChIJh_24QJ-AhYAR_xbUNVN2Xns", 4.6);
INSERT INTO restaurants (name, place_id, rating) VALUES ("The Grove - Hayes Valley", "ChIJIVD-WqKAhYAReHbjHnhsCNw", 4.1);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Flour + Water", "ChIJDVaCXjd-j4AR4AOGUS0kLGc", 4.4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("The Brixton", "ChIJr066l9qAhYARBzcA3aD1zXM", 3.9);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Bluestem Brasserie", "ChIJD3SSEnyAhYARIINe4K2QH48", 4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Cafe Claude", "ChIJSdzjdYmAhYARb5BhktWOSg4", 4.1);
INSERT INTO restaurants (name, place_id, rating) VALUES ("E&O Kitchen and Bar", "ChIJGXWXQYmAhYAR-Nr_OyKvI2o", 4.2);
INSERT INTO restaurants (name, place_id, rating) VALUES ("DNA Lounge", "ChIJc_iInSh-j4ARUkdU9Rr5lFI", 4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Nihon Whisky Lounge", "ChIJX1E5fyZ-j4ARjujgYYPmhWA", 4.2);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Tadich Grill", "ChIJqVjXkGGAhYAR5X80yCKz9Wo", 4.2);
INSERT INTO restaurants (name, place_id, rating) VALUES ("The Cheesecake Factory", "ChIJG-PkK4-AhYARxW6vm0X9kCQ", 3.8);
INSERT INTO restaurants (name, place_id, rating) VALUES ("NorthStar Cafe", "ChIJ5VRAhfGAhYARwiCDOFwBycs", 4.6);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Tropisueño", "ChIJfcaly4eAhYARSIvvfFpH64w", 4.2);
INSERT INTO restaurants (name, place_id, rating) VALUES ("In-N-Out Burger", "ChIJcUlD0eOAhYARucGJj8eN9I8", 4.2);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Amber", "ChIJD8yVgoiAhYAR6Hl-j7OC2I8", 4.1);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Mama's", "ChIJzXSCqfGAhYAR_AM6FCI7To4", 4.2);
INSERT INTO restaurants (name, place_id, rating) VALUES ("The Big 4", "ChIJo_6Ueo2AhYARsBQcUwYK84Y", 4.3);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Absinthe Brasserie & Bar", "ChIJ1T-IlZiAhYAR5m-Mps4qLFk", 4.2);
INSERT INTO restaurants (name, place_id, rating) VALUES ("John's Grill", "ChIJe9MuVY-AhYARb8Su4vUOneY", 4.1);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Super Duper Burgers", "ChIJLVgtY4iAhYARoO_UxqNv5Bw", 4.4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Epic Steak", "ChIJJVhdD3CAhYARw2KuKNaUCEg", 4.3);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Taquería El Farolito", "ChIJ5WRITUd-j4ARIcl68TeeR8M", 4.5);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Gracias Madre", "ChIJH3SFojx-j4AR-ceZkVNV7PA", 4.3);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Greens Restaurant", "ChIJceeAXt6AhYARur0rWLmvt1A", 4.1);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Leopold's", "ChIJu-LEaOiAhYAR6aVCXxJ3yxk", 4.5);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Hi Dive Bar", "ChIJg4pqPXGAhYAR0UA0NWHHPPo", 4.2);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Twenty Five Lusk", "ChIJAzkmQNZ_j4ARs6PNLtDYE_g", 4.3);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Condor Club", "ChIJW2osevSAhYAROH3ZYHbA8Ao", 3.9);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Nickies", "ChIJ3UgDy6aAhYARdyIqpQ7ZoxU", 4.2);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Tony's Pizza Napoletana", "ChIJHXHcEvGAhYARQPuHNN78s78", 4.5);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Alexander's Steakhouse", "ChIJVST7ANZ_j4ARbkYi2s36GQ8", 4.5);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Wonderland", "ChIJ5Z8qxqaAhYARm_WgusAlTrU", 4.3);
INSERT INTO restaurants (name, place_id, rating) VALUES ("North Beach Pizza", "ChIJx8TcWlGHhYAR2kONDWjdWp8", 3.5);
INSERT INTO restaurants (name, place_id, rating) VALUES ("House of Prime Rib", "ChIJg67caeqAhYAR2UQjKb1a8j4", 4.6);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Jillian's", "ChIJ-zhtDYeAhYARMeFTplM45o4", 3.4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("b. patisserie", "ChIJ59WgYcmAhYARu5gLD0FVpw4", 4.7);
INSERT INTO restaurants (name, place_id, rating) VALUES ("IHOP", "ChIJ6yZkrPyAhYARhLLDCEaXjjU", 3.9);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Pancho Villa Taqueria", "ChIJJ50NrSN-j4ARtLkebWzfDGc", 4.3);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Barbacco", "ChIJLy7wmmGAhYARmJLWwob3AnQ", 4.2);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Chipotle Mexican Grill", "ChIJLXQNRWKAhYARP1JWKlUSl4M", 3.8);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Gold Club", "ChIJqUq8D32AhYARdLzkgdNNfts", 3.3);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Sorabol BBQ Restaurant", "ChIJy4EsVWSAhYARsWb50o0xh3Q", 3.5);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Zero Zero", "ChIJ-VtspYCAhYAR1NlEgy5ye6o", 4.3);
INSERT INTO restaurants (name, place_id, rating) VALUES ("The Monk's Kettle", "ChIJT_B1bCJ-j4ARA074-UL3mkY", 4.3);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Foreign Cinema", "ChIJPwvLyD5-j4AR2fM8C0bbVC8", 4.3);
INSERT INTO restaurants (name, place_id, rating) VALUES ("The Sycamore", "ChIJ0WvRSyN-j4ARpvLPuZyI3l4", 4.4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Gary Danko", "ChIJq342JeGAhYARwdtH9tlX7gg", 4.5);
INSERT INTO restaurants (name, place_id, rating) VALUES ("State Bird Provisions", "ChIJQ7kGpLmAhYARKeCe2pDobWk", 4.6);
INSERT INTO restaurants (name, place_id, rating) VALUES ("The Irish Bank", "ChIJO-TDcImAhYAR6O16Hgw4feE", 4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Auntie Anne's Pretzels", "ChIJy4kpbIaAhYAR_yxhR0Amrwk", 4.1);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Per Diem", "ChIJs-CCd2KAhYAR8Ru06zrZe6c", 4.3);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Dosa on Fillmore", "ChIJV0-YWbiAhYARBNSks82WU90", 4.2);
INSERT INTO restaurants (name, place_id, rating) VALUES ("SUBWAY®Restaurants", "ChIJH7p4BeqAhYARARZw4y2tJ7U", 3.5);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Le Colonial", "ChIJa9G9A46AhYARiUmFxVtWcgk", 4.1);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Sushirrito", "ChIJ59q8pmKAhYAR0tfR_s2qwak", 4.2);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Palomino", "ChIJm-rUoHqAhYARyckcbO8yHSs", 3.8);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Bullitt", "ChIJm8SgsemAhYARTmVCgasENMw", 3.9);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Roka Akor", "ChIJjcHJL_WAhYARt6iTSV07hd8", 4.6);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Bottom of the Hill", "ChIJQcdLBsx_j4AROyDSIMBYKH8", 4.5);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Yank Sing (Stevenson Street)", "ChIJ1aUl92KAhYARTY_D5x-dTnE", 4.1);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Zeitgeist", "ChIJU889QiB-j4ARzQofqaFrMJU", 4.1);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Spruce", "ChIJ_075ezGHhYARMb6UkSpmbbE", 4.6);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Rosa Mexicano", "ChIJ39p3NWSAhYAR0M9_pMRICJk", 4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Ozumo", "ChIJJRHaqGWAhYARpXxUOdyMox0", 4.3);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Mikkeller Bar", "ChIJ2WwqkYWAhYARLyKUhwqq2Zk", 4.5);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Il Fornaio San Francisco", "ChIJEzzAJPaAhYARXNaBo1UeFJU", 4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Waterfront Restaurant", "ChIJu6kOQV6AhYARD3bFxmyGqqY", 4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("The Pink Elephant Alibi", "ChIJRwAoRH2AhYAR-AlsWfLuTLw", 4.3);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Biergarten", "ChIJp4nrB6KAhYARhS8cKd1vZ5Q", 4.4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Morton's The Steakhouse", "ChIJBVKvlI6AhYARrCCeLtqco2U", 4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Anchor & Hope", "ChIJaWduK32AhYARvGPmEG2yrWA", 4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Town Hall Restaurant", "ChIJs6-YsWSAhYAR_9_dvdFDUww", 4.1);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Ajisen Ramen San Francisco", "ChIJ6zMe3oWAhYAR5VJ5_NjWQT8", 3.9);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Prospect", "ChIJsc_3vHqAhYARG50dM6228cE", 4.3);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Espetus Churrascaria", "ChIJ66_qpZ-AhYARfNS4aKMMIog", 4.3);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Bouche", "ChIJaa9OAYyAhYARxwgUHLNEpOY", 4.6);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Pier 23 Cafe", "ChIJZX_ij1iAhYARD_4FwphAcN0", 4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Honey Honey Cafe & Crepery", "ChIJJ5FAFI6AhYARWc6pWHaIZZE", 4.2);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Cotogna", "ChIJA0YvGPWAhYAReXmaDTTdWzU", 4.5);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Hard Rock Cafe", "ChIJHSGzi_yAhYARjust_4pPIbc", 3.6);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Original Joe's", "ChIJfSGLEfGAhYARC8Egs7nINzk", 4.4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Bar Agricole", "ChIJCSdjKSZ-j4ARY5HrLSxbatQ", 4.1);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Johnny Foley's Irish House", "ChIJYQrxFI-AhYARSkQbx58DuHE", 4.2);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Delancey Street Restaurant", "ChIJTRf2DXeAhYARsjppfRXu44s", 4.3);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Umami Burger", "ChIJ5R8Cn9qAhYAR97rbI4enNm8", 4.1);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Soma StrEat Food Park", "ChIJeaJ_sSh-j4AR7jS8-7l5qgw", 4.3);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Craftsman and Wolves", "ChIJc3PCIT1-j4ARgxykctQlAaY", 4.5);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Lao Table", "ChIJlzpQKH2AhYARxeGIpYu53Tw", 4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Panera Bread", "ChIJE2LZxdZ_j4ARiHdcMRU_tSQ", 3.9);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Bar Crudo", "ChIJG5eZAYyAhYARoc7-JK2NJEU", 4.5);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Little Star Pizza", "ChIJzf0lTbCAhYARqz-tqaIyJaY", 4.5);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Starbelly", "ChIJs6YBYhx-j4AR4LUJq9SFQt0", 4.2);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Bob's Steak & Chop House", "ChIJDzxeQ4qAhYARht0iLm2i0XQ", 4.1);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Boudin Bakery", "ChIJjfdYMWGAhYARaiF9A6P1Ozc", 3.9);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Roy's Restaurant", "ChIJrwxH0GKAhYARMK9ZdZNa3EA", 4.1);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Chipotle Mexican Grill", "ChIJLXQNRWKAhYAROSIPOmw_oRI", 4.1);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Hillstone", "ChIJ3a33xfmAhYAR5tbOg8ouvf8", 4.4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Magnolia Gastropub and Brewery", "ChIJE0grwKyAhYARYEGINq3LTPQ", 4.2);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Rainforest Cafe", "ChIJ1wPjDeOAhYARX_OfALro_Tk", 3.7);
INSERT INTO restaurants (name, place_id, rating) VALUES ("TRES", "ChIJTxXE6Nd_j4ARtj7K1--pYQY", 3.9);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Plow", "ChIJRT-pgcl_j4ARC1TrxZcQ8xY", 4.5);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Central Kitchen", "ChIJr-EMFjd-j4ARHKaF3ehlmgY", 4.4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Cowgirl Creamery Sidekick Cafe & Milk Bar", "ChIJeTojGF-AhYARE7vVjdf5r-k", 4.1);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Salt House", "ChIJRU1AJ2OAhYARFA9ToMGw-OE", 4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Hard Water", "ChIJSYqwTGeAhYARXBQKB6Qwics", 4.4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Tommy's Joynt", "ChIJUyoRf5aAhYAR4449E3H2WiQ", 4.3);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Boudin Bakery & Cafe", "ChIJFYH6EeOAhYARbqzlQZoIRD8", 4.3);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Suppenküche", "ChIJ8fbCTqKAhYAR9Uu7AyP5FyE", 4.4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Bix", "ChIJDZ0ZOPWAhYARkZFd-uCioMs", 4.3);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Parallel 37", "ChIJf17NcIyAhYARjeQrOo_ATpY", 4.6);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Specialty's Cafe & Bakery", "ChIJISwjSH2AhYARWlfdCYxBpWw", 3.9);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Quince", "ChIJ8biHnb-AhYARSpU8MDPb5vs", 4.6);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Ryoko's Japanese Restaurant & Bar", "ChIJUem7D46AhYARYUQXakltDSo", 4.4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Barneys Gourmet Hamburgers", "ChIJMR41dxJ-j4ARUBkGVC_A0Us", 4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Americano", "ChIJOWCTNGSAhYARdqrrGbwF_QI", 3.9);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Nopalito", "ChIJWdx6WK6AhYARchLwAKyG4-Y", 4.3);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Osha Thai Restaurant & Lounge", "ChIJ421bSGGAhYARogZJrPFCrOU", 4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Mission Chinese Food", "ChIJmZN_ljx-j4ARF16HqVQ2vnI", 4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Original Buffalo Wings", "ChIJCzcaDdSAhYARkR-HB8Y5dr8", 3.5);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Michael Mina", "ChIJX5_Yk2GAhYARaRwC-z9Xig8", 4.5);
INSERT INTO restaurants (name, place_id, rating) VALUES ("F8 Nightclub & Bar", "ChIJm5TigIKAhYARZ_AATy2Ieu4", 4.2);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Scala's Bistro", "ChIJk6jRv46AhYARbE6mIQ6VDsg", 4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Serpentine", "ChIJf5sXibl_j4AR5wRLyjqQelU", 4.3);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Jade Cafe", "ChIJ272z2i9-j4AR3VlvNJCCDlE", 4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Limón Rotisserie", "ChIJkz3yWSJ-j4AR5EejAF8BaLU", 4.2);
INSERT INTO restaurants (name, place_id, rating) VALUES ("5A5 Steak Lounge", "ChIJ8WWHCWCAhYARe-V1QBpRVAU", 4.2);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Southside Spirit House", "ChIJHzz-wXyAhYARha8nlCgjEYw", 4.2);
INSERT INTO restaurants (name, place_id, rating) VALUES ("HRD", "ChIJVciqzniAhYARoFZH_DAD8QI", 4.4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Bisou Bistronomy", "ChIJPc_WpRx-j4AR5xmnSgDgB0A", 4.2);
INSERT INTO restaurants (name, place_id, rating) VALUES ("The Keystone Social House", "ChIJRcqFN4aAhYARSvdFY6nNytM", 4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Top of the Mark", "ChIJp1S1Bo2AhYARewugVNy_l4g", 4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Sears Fine Food", "ChIJlW39lY6AhYAR-kYSJfvNY6A", 4.2);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Schroeder's", "ChIJe0MyoGGAhYARJsBsUHgM8mg", 4);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Hollywood Cafe", "ChIJF7AFf-SAhYARJPDwj0CBm14", 4.5);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Mad Dog in the Fog", "ChIJl7WTv6aAhYAR-PflVqm6yoY", 3.9);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Bobo's", "ChIJgYQEod2AhYARB-mbuMUyGhw", 4.1);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Taco Bell", "ChIJUcXYWWGAhYARmjMY2bJAG2s", 2.7);
INSERT INTO restaurants (name, place_id, rating) VALUES ("YamaSho", "ChIJeanPM5SAhYARLvgC3mxgDoA", 4.2);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Wise Sons Jewish Delicatessen", "ChIJvZgJ50B-j4ARppfRLFvDvc4", 4.3);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Hops & Hominy", "ChIJtSIPQImAhYARdWljrkbLzDM", 4.3);
INSERT INTO restaurants (name, place_id, rating) VALUES ("Puccini & Pinetti", "ChIJ-WNBZ4-AhYAR9Y2WG1sRo7Q", 3.6);
